# Generated by Django 3.1.1 on 2020-09-11 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Nazov', max_length=200)),
                ('author', models.CharField(blank=True, default='Pani doktorka', max_length=200, null=True)),
                ('announcement', models.TextField(default='Oznam')),
                ('date', models.DateField()),
            ],
        ),
    ]
