# Generated by Django 3.1.1 on 2020-09-07 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='author',
            field=models.CharField(blank=True, default='Pani doktorka', max_length=200, null=True),
        ),
    ]
